Algoritmo "questão 1"
 var
  n1, n2, soma, sub, mult, divi: real

 inicio
  escreva("Digite o primeiro número: ")
  leia(n1)
  escreva("Digite o segundo número: ")
  leia(n2)

 soma <- n1+n2
 sub <- n1-n2
 mult <- n1*n2
 divi <-n1/n2

 escreval("A soma é: ",n1+n2)
 escreval("A subtração é: ",n1-n2)
 escreval("A multiplicação é: ",n1*n2)
 escreval("A divisão é: ",n1/n2)

Fimalgoritmo